package app;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rgodo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        background = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        passwordlabel = new javax.swing.JLabel();
        passwordbox = new javax.swing.JPasswordField();
        userlabel = new javax.swing.JLabel();
        userbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BG2.jpg"))); // NOI18N
        panel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 820, -1));

        signup.setBackground(new java.awt.Color(255, 255, 153));
        signup.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        signup.setText("Iniciar Sesion");
        signup.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signup.setBorderPainted(false);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        panel.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 140, 40));

        passwordlabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        passwordlabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel.setText("Contraseña");
        panel.add(passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 30));

        passwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordboxActionPerformed(evt);
            }
        });
        panel.add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        userlabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userlabel.setForeground(new java.awt.Color(255, 255, 255));
        userlabel.setText("Nombre");
        panel.add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 30));

        userbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(null));
        userbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userboxActionPerformed(evt);
            }
        });
        panel.add(userbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 320, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSPARENCIA, RAPIDEZ Y EFICIENCIA AL MEJOR PRECIO");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo1.png"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 380, 270));

        exit.setBackground(new java.awt.Color(255, 255, 153));
        exit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 130, 40));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userboxActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        String user = "user";
        String pass = "1234";
        String admin = "admin";
        String adminpass = "1234";
        
        if (user.equals(userbox.getText())){
            String password="";
            
            for(int i=0;i<passwordbox.getPassword().length;i++){
                password += passwordbox.getPassword()[i];
            }
            if (pass.equals(password)){
                Operation userapp = new Operation();
                userapp.setVisible(true);
                
                dispose();
                
            }else
                JOptionPane.showMessageDialog(null, "Error en contraseña");
        }
        else if (admin.equals(userbox.getText())){
            String password="";
            
            for(int i=0;i<passwordbox.getPassword().length;i++){
                password += passwordbox.getPassword()[i];
            }
            if (adminpass.equals(password)){
                Admin adminapp = new Admin();
                adminapp.setVisible(true);
                
                dispose();
            }else
                JOptionPane.showMessageDialog(null, "Error en contraseña");
        
        }else
            
     
        JOptionPane.showMessageDialog(null, "Error, Ususario desconosido");
    }//GEN-LAST:event_signupActionPerformed

    private void passwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passwordbox;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JButton signup;
    private javax.swing.JTextField userbox;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
