/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author rgodo
 */
public class Operation extends javax.swing.JFrame {
    private static Double usachange;
    private static Double eurchange;
    private static Double bolchange;
    private static Double solchange;
    private static Double colchange;
    private static Double argchange;
    private static Double canchange;
    private static Double mexchange;

    /**
     * Creates new form operation
     */
    public Operation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        buymoney = new javax.swing.JRadioButton();
        sellmoney = new javax.swing.JRadioButton();
        getmoney = new javax.swing.JRadioButton();
        outmoney = new javax.swing.JLabel();
        simbol = new javax.swing.JLabel();
        moneyexchange = new javax.swing.JTextField();
        usaconvert = new javax.swing.JButton();
        eurconvert = new javax.swing.JButton();
        boilconvert = new javax.swing.JButton();
        solconvert = new javax.swing.JButton();
        argconvert = new javax.swing.JButton();
        colconvert = new javax.swing.JButton();
        canconvert = new javax.swing.JButton();
        mexconvert = new javax.swing.JButton();
        acceptbutton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        filemenu = new javax.swing.JMenu();
        logoutmenu = new javax.swing.JCheckBoxMenuItem();
        exitmenu = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(buymoney);
        buymoney.setText("Comprar");
        buymoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buymoneyActionPerformed(evt);
            }
        });
        jPanel2.add(buymoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        buttonGroup1.add(sellmoney);
        sellmoney.setText("Vender");
        jPanel2.add(sellmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        buttonGroup1.add(getmoney);
        getmoney.setText("Girar");
        jPanel2.add(getmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        outmoney.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        outmoney.setText("0");
        jPanel2.add(outmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 170, 70));

        simbol.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        simbol.setText("$");
        jPanel2.add(simbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 20, 90));

        moneyexchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyexchangeMouseClicked(evt);
            }
        });
        moneyexchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyexchangeActionPerformed(evt);
            }
        });
        jPanel2.add(moneyexchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 280, 60));

        usaconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midusaflag.png"))); // NOI18N
        usaconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usaconvertActionPerformed(evt);
            }
        });
        jPanel2.add(usaconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, 40));

        eurconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midEuropean-Union-Flag-icon.png"))); // NOI18N
        eurconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eurconvertActionPerformed(evt);
            }
        });
        jPanel2.add(eurconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, 50));

        boilconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midbolivianflagpng.png"))); // NOI18N
        boilconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boilconvertActionPerformed(evt);
            }
        });
        jPanel2.add(boilconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, 50));

        solconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midperuflag.png"))); // NOI18N
        solconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solconvertActionPerformed(evt);
            }
        });
        jPanel2.add(solconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 60, 50));

        argconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midargentinaflag.png"))); // NOI18N
        argconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                argconvertActionPerformed(evt);
            }
        });
        jPanel2.add(argconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 60, 50));

        colconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midcolombiaflag.png"))); // NOI18N
        colconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colconvertActionPerformed(evt);
            }
        });
        jPanel2.add(colconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, 50));

        canconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midcanadaflag.png"))); // NOI18N
        canconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canconvertActionPerformed(evt);
            }
        });
        jPanel2.add(canconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 60, 50));

        mexconvert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midmexicanflag.png"))); // NOI18N
        mexconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mexconvertActionPerformed(evt);
            }
        });
        jPanel2.add(mexconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 60, 50));

        acceptbutton.setBackground(new java.awt.Color(255, 255, 153));
        acceptbutton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        acceptbutton.setText("TOTAL");
        acceptbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(acceptbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 160, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 530));

        filemenu.setText("Archivo");

        logoutmenu.setText("Cerrar Sesion");
        logoutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuActionPerformed(evt);
            }
        });
        filemenu.add(logoutmenu);

        exitmenu.setText("Salir");
        exitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuActionPerformed(evt);
            }
        });
        filemenu.add(exitmenu);

        jMenuBar1.add(filemenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buymoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buymoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buymoneyActionPerformed

    private void logoutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuActionPerformed
        Login logout = new Login();
        logout.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutmenuActionPerformed

    private void moneyexchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyexchangeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyexchangeMouseClicked

    private void moneyexchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyexchangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyexchangeActionPerformed

    private void usaconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usaconvertActionPerformed
    usachange = Double.parseDouble(moneyexchange.getText());
    
    if(usachange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(usachange * Admin.usatotal));
        
    }
    }//GEN-LAST:event_usaconvertActionPerformed

    private void eurconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eurconvertActionPerformed
         eurchange = Double.parseDouble(moneyexchange.getText());
    
    if(eurchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(eurchange * Admin.eurtotal));
        
    }
    }//GEN-LAST:event_eurconvertActionPerformed

    private void boilconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boilconvertActionPerformed
            bolchange = Double.parseDouble(moneyexchange.getText());
    
    if(bolchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(bolchange * Admin.boltotal));
        
    }
    }//GEN-LAST:event_boilconvertActionPerformed

    private void solconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solconvertActionPerformed
          solchange = Double.parseDouble(moneyexchange.getText());
    
    if(solchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(solchange * Admin.soltotal));
        
    }
    }//GEN-LAST:event_solconvertActionPerformed

    private void argconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_argconvertActionPerformed
          argchange = Double.parseDouble(moneyexchange.getText());
    
    if(argchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(argchange * Admin.argtotal));
        
    }
    }//GEN-LAST:event_argconvertActionPerformed

    private void mexconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexconvertActionPerformed
          mexchange = Double.parseDouble(moneyexchange.getText());
    
    if(mexchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(mexchange * Admin.mextotal));
        
    }
    }//GEN-LAST:event_mexconvertActionPerformed

    private void colconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colconvertActionPerformed
          colchange = Double.parseDouble(moneyexchange.getText());
    
    if(colchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(colchange * Admin.coltotal));
        
    }
    }//GEN-LAST:event_colconvertActionPerformed

    private void acceptbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptbuttonActionPerformed
      if(buymoney.isSelected()==false && sellmoney.isSelected()==false && getmoney.isSelected()==false)
    {
        JOptionPane.showMessageDialog(null,"No selecciono ninguna opción");
    }else if(buymoney.isSelected()==true && sellmoney.isSelected()==false && getmoney.isSelected()==false)
        
    {
        Bills bill = new Bills();
        bill.setVisible(true);
        
        dispose();
        Bills.totallabel.setText(Double.toString(usachange * Admin.usatotal));

    }else if(buymoney.isSelected()==false && sellmoney.isSelected()==true && getmoney.isSelected()==false)
        
    {
        Bills bill = new Bills();
        bill.setVisible(true);
        
        dispose();
        Bills.totallabel.setText(Double.toString(usachange * Admin.usatotal));
    }else if(buymoney.isSelected()==false && sellmoney.isSelected()==false && getmoney.isSelected()==true)
        
    {
        Bills bill = new Bills();
        bill.setVisible(true);
        
        dispose();
        Bills.totallabel.setText(Double.toString(usachange * Admin.usatotal));

    }//GEN-LAST:event_acceptbuttonActionPerformed
    }
    private void canconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canconvertActionPerformed
          canchange = Double.parseDouble(moneyexchange.getText());
    
    if(canchange <=0){
       JOptionPane.showMessageDialog(null, "Valor de cambio no puede ser inferior a 0");
    }else{
        outmoney.setText(Double.toString(canchange * Admin.cantotal));
        
    }
    }//GEN-LAST:event_canconvertActionPerformed

    private void exitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitmenuActionPerformed

 
    public static void main(String args[]){
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Operation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptbutton;
    private javax.swing.JButton argconvert;
    private javax.swing.JButton boilconvert;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buymoney;
    private javax.swing.JButton canconvert;
    private javax.swing.JButton colconvert;
    private javax.swing.JButton eurconvert;
    private javax.swing.JCheckBoxMenuItem exitmenu;
    private javax.swing.JMenu filemenu;
    private javax.swing.JRadioButton getmoney;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBoxMenuItem logoutmenu;
    private javax.swing.JButton mexconvert;
    private javax.swing.JTextField moneyexchange;
    private javax.swing.JLabel outmoney;
    private javax.swing.JRadioButton sellmoney;
    private javax.swing.JLabel simbol;
    private javax.swing.JButton solconvert;
    private javax.swing.JButton usaconvert;
    // End of variables declaration//GEN-END:variables
}
